# language type:
language: cpp

# compilator system:
compiler:
- clang
- gcc

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git clone https://github.com/HeeroYui/ewol.git
  - cd ewol; git checkout origin/dev -b dev; cd ..
  - cd ewol; git submodule init; cd ..
  - cd ewol; git submodule update; cd ..

install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then sudo rm /usr/bin/gcc /usr/bin/g++; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++; fi
  - if [ "$CXX" == "clang++" ]; then wget http://llvm.org/releases/3.4.1/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz; fi
  - if [ "$CXX" == "clang++" ]; then tar xJf clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz; fi
  - if [ "$CXX" == "clang++" ]; then export PATH=$PWD/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04/bin:$PATH; fi

# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./ewol/build/lutin.py -cclang -mdebug -p edn; fi
  - if [ "$CXX" == "g++" ]; then ./ewol/build/lutin.py -cgcc -mdebug -p edn; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
