# language type:
language: cpp

# compilator system:
compiler:
- clang
- gcc

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git clone https://github.com/HeeroYui/ewol.git
  - cd ewol; git checkout origin/dev -b dev; cd ..
  - cd ewol; git submodule init; cd ..
  - cd ewol; git submodule update; cd ..

#install Gcc to have lisstdc++ 4.8 & gcc 4.8
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./ewol/build/lutin.py -C -P -cclang -mdebug -p edn; fi
  - if [ "$CXX" == "g++" ]; then ./ewol/build/lutin.py -C -P -cgcc -mdebug -p edn; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
